version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: vodang-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: green_mindmap_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vodang.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    ports:
      - "85:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: green_mindmap_redis
    environment:
      REDIS_PASSWORD: 12345678
    ports:
      - "6379:6379"

volumes:
  pgadmin_data:
  postgres_data: