import { MigrationInterface, QueryRunner } from "typeorm";

export class InitDB1756397010076 implements MigrationInterface {
    name = 'InitDB1756397010076'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "locations_users_id_fk"`);
        await queryRunner.query(`ALTER TABLE "food_items" DROP CONSTRAINT "ca"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "invoices_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "invoices_scan_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "scans" DROP CONSTRAINT "scans_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "scans" DROP CONSTRAINT "scans_food_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_big_five_id_fk"`);
        await queryRunner.query(`ALTER TABLE "behaviors" DROP CONSTRAINT "behaviors_thread_halls_id_fk"`);
        await queryRunner.query(`CREATE TABLE "tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying(255) NOT NULL, "deviceID" character varying(50), "expiredAt" TIMESTAMP NOT NULL, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6a8ca5961656d13c16c04079dd3" UNIQUE ("token"), CONSTRAINT "UQ_6e88a0a447be3fa009b4051c196" UNIQUE ("deviceID"), CONSTRAINT "PK_3001e89ada36263dabf1fb6210a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "latiude"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "big_five" DROP COLUMN "openess"`);
        await queryRunner.query(`ALTER TABLE "food_items" DROP COLUMN "calorie_id"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "scan_id"`);
        await queryRunner.query(`ALTER TABLE "scans" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "scans" DROP COLUMN "food_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "big_five_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "permisson"`);
        await queryRunner.query(`ALTER TABLE "templates" DROP COLUMN "placeholders"`);
        await queryRunner.query(`ALTER TABLE "behaviors" DROP COLUMN "thread_hall_ids"`);
        await queryRunner.query(`ALTER TABLE "behaviors" DROP COLUMN "keyworkds"`);
        await queryRunner.query(`ALTER TABLE "thread_halls" DROP COLUMN "related_traits"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "template_id"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "thread_hall_id"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "latitude" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "big_five" ADD "openness" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "big_five" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "big_five" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "calories" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "calories" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "food_items" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "food_items" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "food_items" ADD "caloriesId" uuid`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "scansId" uuid`);
        await queryRunner.query(`ALTER TABLE "scans" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "scans" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "scans" ADD "foodItemsId" uuid`);
        await queryRunner.query(`ALTER TABLE "scans" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD "username" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "templates" ADD "placeholder" text array NOT NULL`);
        await queryRunner.query(`ALTER TABLE "templates" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "templates" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "behaviors" ADD "keywords" text array NOT NULL`);
        await queryRunner.query(`ALTER TABLE "behaviors" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "behaviors" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "behaviors" ADD "threadHallId" uuid`);
        await queryRunner.query(`ALTER TABLE "thread_halls" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "thread_halls" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "thread_halls" ADD "traitsId" uuid`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "templateId" uuid`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "threadHallId" uuid`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "locations_pk"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "longitude" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "address" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "big_five" DROP CONSTRAINT "big_five_pkey"`);
        await queryRunner.query(`ALTER TABLE "big_five" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "big_five" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "big_five" ADD CONSTRAINT "PK_2a3478d2ae6405fdf061726b5ff" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "big_five" ALTER COLUMN "conscientiousness" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "big_five" ALTER COLUMN "extraversion" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "big_five" ALTER COLUMN "agreeableness" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "big_five" ALTER COLUMN "neuroticism" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "calories" DROP CONSTRAINT "calories_pkey"`);
        await queryRunner.query(`ALTER TABLE "calories" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "calories" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "calories" ADD CONSTRAINT "PK_fbbaaf701b9370e4a9c2b7e7b07" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "food_items" DROP CONSTRAINT "food_items_pkey"`);
        await queryRunner.query(`ALTER TABLE "food_items" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "food_items" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "food_items" ADD CONSTRAINT "PK_6b37e62b21c674c714a581c59a6" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "food_items" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "food_items" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "food_items" DROP COLUMN "barcode"`);
        await queryRunner.query(`ALTER TABLE "food_items" ADD "barcode" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "invoices_pkey"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "issued_at"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "issued_at" TIME WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scans" DROP CONSTRAINT "scans_pkey"`);
        await queryRunner.query(`ALTER TABLE "scans" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "scans" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "scans" ADD CONSTRAINT "PK_41156c08314b9e541c1cb18c588" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "dateOfBirth" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "templates" DROP CONSTRAINT "templates_pkey"`);
        await queryRunner.query(`ALTER TABLE "templates" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "templates" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "templates" ADD CONSTRAINT "PK_515948649ce0bbbe391de702ae5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "behaviors" DROP CONSTRAINT "behaviors_pkey"`);
        await queryRunner.query(`ALTER TABLE "behaviors" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "behaviors" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "behaviors" ADD CONSTRAINT "PK_dc34a2b981fe38b508ba9957255" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "traits" DROP CONSTRAINT "traits_pkey"`);
        await queryRunner.query(`ALTER TABLE "traits" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "traits" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "traits" ADD CONSTRAINT "PK_3956071aa0a8eb8210aa1c6a563" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "traits" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "traits" ALTER COLUMN "label" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "thread_halls" DROP CONSTRAINT "thread_halls_pkey"`);
        await queryRunner.query(`ALTER TABLE "thread_halls" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "thread_halls" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "thread_halls" ADD CONSTRAINT "PK_09adb0fdf43ef0228e7568631af" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "thread_halls" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "questions_pkey"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "PK_08a6d4b0f49ff300bf3a0ca60ac" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "placeholders" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "expected_answer" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "user_answers_pkey"`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "user_answers_pkey" PRIMARY KEY ("question_id")`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "user_answers_pkey"`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "user_answers_pkey" PRIMARY KEY ("question_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "user_answers_pkey"`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "PK_d84d10f2e3b97a037d5479bf669" PRIMARY KEY ("user_id")`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP COLUMN "question_id"`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD "question_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "PK_d84d10f2e3b97a037d5479bf669"`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "PK_6b98aee2579df632ccb8b36ba49" PRIMARY KEY ("user_id", "question_id")`);
        await queryRunner.query(`ALTER TABLE "user_answers" ALTER COLUMN "answer" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_answers" ALTER COLUMN "timestamp" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "FK_78eda52dc27b7ad20350c4a752d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "food_items" ADD CONSTRAINT "FK_64f0e2dee015dc132a254c0e513" FOREIGN KEY ("caloriesId") REFERENCES "calories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_fcbe490dc37a1abf68f19c5ccb9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_02cd4a1e7eefac58057c27e1454" FOREIGN KEY ("scansId") REFERENCES "scans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scans" ADD CONSTRAINT "FK_57095699a6f103d94285bce1221" FOREIGN KEY ("foodItemsId") REFERENCES "food_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scans" ADD CONSTRAINT "FK_3c9fda05783a207f1bb62777f17" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "behaviors" ADD CONSTRAINT "FK_5afc686724620f4c13d4cf1a29c" FOREIGN KEY ("threadHallId") REFERENCES "thread_halls"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "thread_halls" ADD CONSTRAINT "FK_204ecc176a8ce3f0d835a85840f" FOREIGN KEY ("traitsId") REFERENCES "traits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_f4e45583cbe6aaa143cdfeaae09" FOREIGN KEY ("templateId") REFERENCES "templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_900ccfcf91e174e7e275de127f1" FOREIGN KEY ("threadHallId") REFERENCES "thread_halls"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "FK_d84d10f2e3b97a037d5479bf669" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "FK_adae59e684b873b084be36c5a7a" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD CONSTRAINT "FK_d417e5d35f2434afc4bd48cb4d2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tokens" DROP CONSTRAINT "FK_d417e5d35f2434afc4bd48cb4d2"`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "FK_adae59e684b873b084be36c5a7a"`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "FK_d84d10f2e3b97a037d5479bf669"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_900ccfcf91e174e7e275de127f1"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_f4e45583cbe6aaa143cdfeaae09"`);
        await queryRunner.query(`ALTER TABLE "thread_halls" DROP CONSTRAINT "FK_204ecc176a8ce3f0d835a85840f"`);
        await queryRunner.query(`ALTER TABLE "behaviors" DROP CONSTRAINT "FK_5afc686724620f4c13d4cf1a29c"`);
        await queryRunner.query(`ALTER TABLE "scans" DROP CONSTRAINT "FK_3c9fda05783a207f1bb62777f17"`);
        await queryRunner.query(`ALTER TABLE "scans" DROP CONSTRAINT "FK_57095699a6f103d94285bce1221"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_02cd4a1e7eefac58057c27e1454"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_fcbe490dc37a1abf68f19c5ccb9"`);
        await queryRunner.query(`ALTER TABLE "food_items" DROP CONSTRAINT "FK_64f0e2dee015dc132a254c0e513"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "FK_78eda52dc27b7ad20350c4a752d"`);
        await queryRunner.query(`ALTER TABLE "user_answers" ALTER COLUMN "timestamp" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_answers" ALTER COLUMN "answer" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "PK_6b98aee2579df632ccb8b36ba49"`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "PK_d84d10f2e3b97a037d5479bf669" PRIMARY KEY ("user_id")`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP COLUMN "question_id"`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD "question_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "PK_d84d10f2e3b97a037d5479bf669"`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "user_answers_pkey" PRIMARY KEY ("question_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "user_answers_pkey"`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "user_answers_pkey" PRIMARY KEY ("question_id")`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD "user_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "user_answers_pkey"`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "user_answers_pkey" PRIMARY KEY ("user_id", "question_id")`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "expected_answer" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "placeholders" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "PK_08a6d4b0f49ff300bf3a0ca60ac"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "questions_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "thread_halls" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "thread_halls" DROP CONSTRAINT "PK_09adb0fdf43ef0228e7568631af"`);
        await queryRunner.query(`ALTER TABLE "thread_halls" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "thread_halls" ADD "id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "thread_halls" ADD CONSTRAINT "thread_halls_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "traits" ALTER COLUMN "label" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "traits" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "traits" DROP CONSTRAINT "PK_3956071aa0a8eb8210aa1c6a563"`);
        await queryRunner.query(`ALTER TABLE "traits" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "traits" ADD "id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "traits" ADD CONSTRAINT "traits_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "behaviors" DROP CONSTRAINT "PK_dc34a2b981fe38b508ba9957255"`);
        await queryRunner.query(`ALTER TABLE "behaviors" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "behaviors" ADD "id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "behaviors" ADD CONSTRAINT "behaviors_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "templates" DROP CONSTRAINT "PK_515948649ce0bbbe391de702ae5"`);
        await queryRunner.query(`ALTER TABLE "templates" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "templates" ADD "id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "templates" ADD CONSTRAINT "templates_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "dateOfBirth" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying`);
        await queryRunner.query(`ALTER TABLE "scans" DROP CONSTRAINT "PK_41156c08314b9e541c1cb18c588"`);
        await queryRunner.query(`ALTER TABLE "scans" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "scans" ADD "id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scans" ADD CONSTRAINT "scans_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "issued_at"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "issued_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "invoices_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "food_items" DROP COLUMN "barcode"`);
        await queryRunner.query(`ALTER TABLE "food_items" ADD "barcode" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "food_items" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "food_items" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "food_items" DROP CONSTRAINT "PK_6b37e62b21c674c714a581c59a6"`);
        await queryRunner.query(`ALTER TABLE "food_items" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "food_items" ADD "id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "food_items" ADD CONSTRAINT "food_items_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "calories" DROP CONSTRAINT "PK_fbbaaf701b9370e4a9c2b7e7b07"`);
        await queryRunner.query(`ALTER TABLE "calories" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "calories" ADD "id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "calories" ADD CONSTRAINT "calories_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "big_five" ALTER COLUMN "neuroticism" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "big_five" ALTER COLUMN "agreeableness" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "big_five" ALTER COLUMN "extraversion" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "big_five" ALTER COLUMN "conscientiousness" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "big_five" DROP CONSTRAINT "PK_2a3478d2ae6405fdf061726b5ff"`);
        await queryRunner.query(`ALTER TABLE "big_five" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "big_five" ADD "id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "big_five" ADD CONSTRAINT "big_five_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "address" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "longitude" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "PK_7cc1c9e3853b94816c094825e74"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "locations_pk" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "threadHallId"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "templateId"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "thread_halls" DROP COLUMN "traitsId"`);
        await queryRunner.query(`ALTER TABLE "thread_halls" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "thread_halls" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "behaviors" DROP COLUMN "threadHallId"`);
        await queryRunner.query(`ALTER TABLE "behaviors" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "behaviors" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "behaviors" DROP COLUMN "keywords"`);
        await queryRunner.query(`ALTER TABLE "templates" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "templates" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "templates" DROP COLUMN "placeholder"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "scans" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "scans" DROP COLUMN "foodItemsId"`);
        await queryRunner.query(`ALTER TABLE "scans" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "scans" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "scansId"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "food_items" DROP COLUMN "caloriesId"`);
        await queryRunner.query(`ALTER TABLE "food_items" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "food_items" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "calories" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "calories" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "big_five" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "big_five" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "big_five" DROP COLUMN "openness"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "latitude"`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "thread_hall_id" bigint`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "template_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "thread_halls" ADD "related_traits" bigint`);
        await queryRunner.query(`ALTER TABLE "behaviors" ADD "keyworkds" text array NOT NULL`);
        await queryRunner.query(`ALTER TABLE "behaviors" ADD "thread_hall_ids" bigint`);
        await queryRunner.query(`ALTER TABLE "templates" ADD "placeholders" text array`);
        await queryRunner.query(`ALTER TABLE "users" ADD "permisson" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "big_five_id" integer`);
        await queryRunner.query(`ALTER TABLE "scans" ADD "food_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scans" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "scan_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "food_items" ADD "calorie_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "big_five" ADD "openess" double precision`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "latiude" double precision`);
        await queryRunner.query(`DROP TABLE "tokens"`);
        await queryRunner.query(`ALTER TABLE "behaviors" ADD CONSTRAINT "behaviors_thread_halls_id_fk" FOREIGN KEY ("thread_hall_ids") REFERENCES "thread_halls"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_big_five_id_fk" FOREIGN KEY ("big_five_id") REFERENCES "big_five"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scans" ADD CONSTRAINT "scans_food_id_fkey" FOREIGN KEY ("food_id") REFERENCES "food_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scans" ADD CONSTRAINT "scans_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "invoices_scan_id_fkey" FOREIGN KEY ("scan_id") REFERENCES "scans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "invoices_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "food_items" ADD CONSTRAINT "ca" FOREIGN KEY ("calorie_id") REFERENCES "calories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "locations_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
