import { MigrationInterface, QueryRunner } from "typeorm";

export class InitDb1762861772711 implements MigrationInterface {
    name = 'InitDb1762861772711'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "scenario_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" character varying NOT NULL DEFAULT 'not_assigned', "createAt" TIMESTAMP NOT NULL DEFAULT now(), "scenarioId" uuid, "userId" uuid, CONSTRAINT "PK_b4ab2875fe573a9dd586c2258d4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "template_answers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL, "scale" json, "labels" json, "options" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "templateId" character varying, CONSTRAINT "REL_89e4150c9659d3c5b38d40d963" UNIQUE ("templateId"), CONSTRAINT "PK_c9347cc8e36d2995a6512a245c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "templates" ("id" character varying NOT NULL, "name" character varying NOT NULL, "description" text, "intent" character varying NOT NULL, "prompt" text NOT NULL, "used_placeholders" json, "question_type" character varying, "filled_prompt" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_515948649ce0bbbe391de702ae5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "behaviors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "type" text NOT NULL, "keywords" text array NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "description" text, "threadHallId" uuid, CONSTRAINT "PK_dc34a2b981fe38b508ba9957255" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "traits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "description" text NOT NULL, "label" text NOT NULL, CONSTRAINT "PK_3956071aa0a8eb8210aa1c6a563" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "thread_halls" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "description" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "traitsId" uuid, CONSTRAINT "PK_09adb0fdf43ef0228e7568631af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_answers" ("user_id" uuid NOT NULL, "question_id" uuid NOT NULL, "answer" text NOT NULL, "timestamp" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6b98aee2579df632ccb8b36ba49" PRIMARY KEY ("user_id", "question_id"))`);
        await queryRunner.query(`CREATE TABLE "question_options" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "text" text NOT NULL, "value" text NOT NULL, "order" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "questionId" uuid, CONSTRAINT "PK_13be20e51c0738def32f00cf7d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "questions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "question" text NOT NULL, "templateId" character varying, "behaviorInput" text, "behaviorNormalized" text, "normalizeScore" numeric(5,2), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "threadHallId" uuid, CONSTRAINT "PK_08a6d4b0f49ff300bf3a0ca60ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "simulated_survey_scenarios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "totalEligible" integer NOT NULL, "targetCount" integer NOT NULL, "assignedCount" integer NOT NULL DEFAULT '0', "unassignedCount" integer NOT NULL DEFAULT '0', "status" character varying(50) NOT NULL DEFAULT 'completed', "notes" text, "eligibleUsers" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "scenarioId" uuid, "triggeredById" uuid, CONSTRAINT "REL_234b12bdd71919aa950f08a4a4" UNIQUE ("scenarioId"), CONSTRAINT "PK_f97115b372136a12ba8e09c3eee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "survey_scenarios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "min_age" integer NOT NULL, "max_age" integer NOT NULL, "percentage" integer NOT NULL DEFAULT '100', "gender" text, "status" text NOT NULL DEFAULT 'draft', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "locationId" uuid, CONSTRAINT "PK_2a8abdb9af9184093d7f798446d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "latitude" double precision NOT NULL, "longitude" double precision NOT NULL, "address" text, "length_to_previous_location" double precision, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "big_five" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "openness" double precision NOT NULL, "conscientiousness" double precision NOT NULL, "extraversion" double precision NOT NULL, "agreeableness" double precision NOT NULL, "neuroticism" double precision NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "REL_f5c79764cf690eaa8877372659" UNIQUE ("userId"), CONSTRAINT "PK_2a3478d2ae6405fdf061726b5ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "calories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "energy_kcal" double precision NOT NULL, "protein_g" double precision NOT NULL, "fat_g" double precision NOT NULL, "carbs_g" double precision NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fbbaaf701b9370e4a9c2b7e7b07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "food_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "barcode" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "caloriesId" uuid, CONSTRAINT "PK_6b37e62b21c674c714a581c59a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scans" ("id" BIGSERIAL NOT NULL, "scan_time" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "foodItemsId" uuid, "userId" uuid, CONSTRAINT "PK_41156c08314b9e541c1cb18c588" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "phoneNumber" character varying(20), "password" character varying(255) NOT NULL, "fullName" character varying(100), "gender" character varying(10), "location" character varying(50), "role" character varying(50), "dateOfBirth" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_1e3d0240b49c40521aaeb953293" UNIQUE ("phoneNumber"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoice_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "raw_name" text, "brand" text, "category" text, "plant_based" boolean NOT NULL DEFAULT false, "quantity" integer NOT NULL, "unit_price" numeric NOT NULL, "line_total" numeric NOT NULL, "matched_shopping_list" boolean NOT NULL DEFAULT false, "invoiceId" uuid, CONSTRAINT "PK_53b99f9e0e2945e69de1a12b75a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "source_id" text, "currency" text NOT NULL, "payment_method" text NOT NULL, "notes" text, "issued_date" date, "issued_time" TIME, "subtotal" numeric NOT NULL, "discount" numeric NOT NULL, "tax" numeric NOT NULL, "grand_total" numeric NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "vendorId" uuid, "userId" uuid, "scansId" bigint, CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vendors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "address" text NOT NULL, "geo_hint" text, CONSTRAINT "PK_9c956c9797edfae5c6ddacc4e6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "todos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(500) NOT NULL, "completed" boolean NOT NULL DEFAULT false, "parent_id" uuid, "user_id" uuid NOT NULL, "order" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ca8cafd59ca6faaf67995344225" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying(255) NOT NULL, "deviceID" character varying(50), "expiredAt" TIMESTAMP NOT NULL, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6a8ca5961656d13c16c04079dd3" UNIQUE ("token"), CONSTRAINT "UQ_6e88a0a447be3fa009b4051c196" UNIQUE ("deviceID"), CONSTRAINT "PK_3001e89ada36263dabf1fb6210a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pre_app_survey" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "daily_spending" numeric, "daily_spending_sigmoid" numeric, "daily_spending_weight" numeric, "daily_spending_direction" character varying, "daily_spending_alpha" numeric, "spending_variation" integer, "spending_variation_sigmoid" numeric, "spending_variation_weight" numeric, "spending_variation_direction" character varying, "spending_variation_alpha" numeric, "brand_trial" integer, "brand_trial_sigmoid" numeric, "brand_trial_weight" numeric, "brand_trial_direction" character varying, "brand_trial_alpha" numeric, "shopping_list" integer, "shopping_list_sigmoid" numeric, "shopping_list_weight" numeric, "shopping_list_direction" character varying, "shopping_list_alpha" numeric, "daily_distance" numeric, "daily_distance_sigmoid" numeric, "daily_distance_weight" numeric, "daily_distance_direction" character varying, "daily_distance_alpha" numeric, "new_places" integer, "new_places_sigmoid" numeric, "new_places_weight" numeric, "new_places_direction" character varying, "new_places_alpha" numeric, "public_transport" integer, "public_transport_sigmoid" numeric, "public_transport_weight" numeric, "public_transport_direction" character varying, "public_transport_alpha" numeric, "stable_schedule" integer, "stable_schedule_sigmoid" numeric, "stable_schedule_weight" numeric, "stable_schedule_direction" character varying, "stable_schedule_alpha" numeric, "night_outings" integer, "night_outings_sigmoid" numeric, "night_outings_weight" numeric, "night_outings_direction" character varying, "night_outings_alpha" numeric, "healthy_eating" integer, "healthy_eating_sigmoid" numeric, "healthy_eating_weight" numeric, "healthy_eating_direction" character varying, "healthy_eating_alpha" numeric, "social_media" integer, "goal_setting" integer, "mood_swings" integer, "is_completed" boolean NOT NULL DEFAULT false, "completed_at" TIMESTAMP, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_07aae69c8eabc9cbedee3c84d70" UNIQUE ("user_id"), CONSTRAINT "REL_07aae69c8eabc9cbedee3c84d7" UNIQUE ("user_id"), CONSTRAINT "PK_5aef47b268af478bd8c63076b4d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "models" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ocean" text NOT NULL, "behavior" text NOT NULL, "age" text NOT NULL, "location" text NOT NULL, "gender" text NOT NULL, "keywords" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ef9ed7160ea69013636466bf2d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "survey_scenarios_questions_questions" ("surveyScenariosId" uuid NOT NULL, "questionsId" uuid NOT NULL, CONSTRAINT "PK_67aa56f0b342c6145f9beab75e1" PRIMARY KEY ("surveyScenariosId", "questionsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_db5e012d7cb7dc89eb5ad05f93" ON "survey_scenarios_questions_questions" ("surveyScenariosId") `);
        await queryRunner.query(`CREATE INDEX "IDX_82c5b9231e8632d637824d85bc" ON "survey_scenarios_questions_questions" ("questionsId") `);
        await queryRunner.query(`ALTER TABLE "scenario_assignments" ADD CONSTRAINT "FK_fc372c04f9d8ca49d63ada19f9a" FOREIGN KEY ("scenarioId") REFERENCES "survey_scenarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scenario_assignments" ADD CONSTRAINT "FK_a75aa9e067b1ac29c7dd6b2b63f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "template_answers" ADD CONSTRAINT "FK_89e4150c9659d3c5b38d40d9634" FOREIGN KEY ("templateId") REFERENCES "templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "behaviors" ADD CONSTRAINT "FK_5afc686724620f4c13d4cf1a29c" FOREIGN KEY ("threadHallId") REFERENCES "thread_halls"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "thread_halls" ADD CONSTRAINT "FK_204ecc176a8ce3f0d835a85840f" FOREIGN KEY ("traitsId") REFERENCES "traits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "FK_d84d10f2e3b97a037d5479bf669" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "FK_adae59e684b873b084be36c5a7a" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_options" ADD CONSTRAINT "FK_c654af7759a681f1b1addbe35bf" FOREIGN KEY ("questionId") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_f4e45583cbe6aaa143cdfeaae09" FOREIGN KEY ("templateId") REFERENCES "templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_900ccfcf91e174e7e275de127f1" FOREIGN KEY ("threadHallId") REFERENCES "thread_halls"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "simulated_survey_scenarios" ADD CONSTRAINT "FK_234b12bdd71919aa950f08a4a44" FOREIGN KEY ("scenarioId") REFERENCES "survey_scenarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "simulated_survey_scenarios" ADD CONSTRAINT "FK_80cd28ac231072c3dbc1a2cc80e" FOREIGN KEY ("triggeredById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_scenarios" ADD CONSTRAINT "FK_db7977c74d7540baa059bb89d38" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "FK_6315d9b5cb977506b9f747e0974" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "big_five" ADD CONSTRAINT "FK_f5c79764cf690eaa88773726593" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "food_items" ADD CONSTRAINT "FK_64f0e2dee015dc132a254c0e513" FOREIGN KEY ("caloriesId") REFERENCES "calories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scans" ADD CONSTRAINT "FK_57095699a6f103d94285bce1221" FOREIGN KEY ("foodItemsId") REFERENCES "food_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scans" ADD CONSTRAINT "FK_3c9fda05783a207f1bb62777f17" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_7fb6895fc8fad9f5200e91abb59" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_754b22c515e4b1ee18ed31f0b07" FOREIGN KEY ("vendorId") REFERENCES "vendors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_fcbe490dc37a1abf68f19c5ccb9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_02cd4a1e7eefac58057c27e1454" FOREIGN KEY ("scansId") REFERENCES "scans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "todos" ADD CONSTRAINT "FK_5508b1763e832c788cc6b33f2d5" FOREIGN KEY ("parent_id") REFERENCES "todos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "todos" ADD CONSTRAINT "FK_53511787e1f412d746c4bf223ff" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD CONSTRAINT "FK_d417e5d35f2434afc4bd48cb4d2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pre_app_survey" ADD CONSTRAINT "FK_07aae69c8eabc9cbedee3c84d70" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_scenarios_questions_questions" ADD CONSTRAINT "FK_db5e012d7cb7dc89eb5ad05f938" FOREIGN KEY ("surveyScenariosId") REFERENCES "survey_scenarios"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "survey_scenarios_questions_questions" ADD CONSTRAINT "FK_82c5b9231e8632d637824d85bcc" FOREIGN KEY ("questionsId") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "survey_scenarios_questions_questions" DROP CONSTRAINT "FK_82c5b9231e8632d637824d85bcc"`);
        await queryRunner.query(`ALTER TABLE "survey_scenarios_questions_questions" DROP CONSTRAINT "FK_db5e012d7cb7dc89eb5ad05f938"`);
        await queryRunner.query(`ALTER TABLE "pre_app_survey" DROP CONSTRAINT "FK_07aae69c8eabc9cbedee3c84d70"`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP CONSTRAINT "FK_d417e5d35f2434afc4bd48cb4d2"`);
        await queryRunner.query(`ALTER TABLE "todos" DROP CONSTRAINT "FK_53511787e1f412d746c4bf223ff"`);
        await queryRunner.query(`ALTER TABLE "todos" DROP CONSTRAINT "FK_5508b1763e832c788cc6b33f2d5"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_02cd4a1e7eefac58057c27e1454"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_fcbe490dc37a1abf68f19c5ccb9"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_754b22c515e4b1ee18ed31f0b07"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_7fb6895fc8fad9f5200e91abb59"`);
        await queryRunner.query(`ALTER TABLE "scans" DROP CONSTRAINT "FK_3c9fda05783a207f1bb62777f17"`);
        await queryRunner.query(`ALTER TABLE "scans" DROP CONSTRAINT "FK_57095699a6f103d94285bce1221"`);
        await queryRunner.query(`ALTER TABLE "food_items" DROP CONSTRAINT "FK_64f0e2dee015dc132a254c0e513"`);
        await queryRunner.query(`ALTER TABLE "big_five" DROP CONSTRAINT "FK_f5c79764cf690eaa88773726593"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "FK_6315d9b5cb977506b9f747e0974"`);
        await queryRunner.query(`ALTER TABLE "survey_scenarios" DROP CONSTRAINT "FK_db7977c74d7540baa059bb89d38"`);
        await queryRunner.query(`ALTER TABLE "simulated_survey_scenarios" DROP CONSTRAINT "FK_80cd28ac231072c3dbc1a2cc80e"`);
        await queryRunner.query(`ALTER TABLE "simulated_survey_scenarios" DROP CONSTRAINT "FK_234b12bdd71919aa950f08a4a44"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_900ccfcf91e174e7e275de127f1"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_f4e45583cbe6aaa143cdfeaae09"`);
        await queryRunner.query(`ALTER TABLE "question_options" DROP CONSTRAINT "FK_c654af7759a681f1b1addbe35bf"`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "FK_adae59e684b873b084be36c5a7a"`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "FK_d84d10f2e3b97a037d5479bf669"`);
        await queryRunner.query(`ALTER TABLE "thread_halls" DROP CONSTRAINT "FK_204ecc176a8ce3f0d835a85840f"`);
        await queryRunner.query(`ALTER TABLE "behaviors" DROP CONSTRAINT "FK_5afc686724620f4c13d4cf1a29c"`);
        await queryRunner.query(`ALTER TABLE "template_answers" DROP CONSTRAINT "FK_89e4150c9659d3c5b38d40d9634"`);
        await queryRunner.query(`ALTER TABLE "scenario_assignments" DROP CONSTRAINT "FK_a75aa9e067b1ac29c7dd6b2b63f"`);
        await queryRunner.query(`ALTER TABLE "scenario_assignments" DROP CONSTRAINT "FK_fc372c04f9d8ca49d63ada19f9a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82c5b9231e8632d637824d85bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db5e012d7cb7dc89eb5ad05f93"`);
        await queryRunner.query(`DROP TABLE "survey_scenarios_questions_questions"`);
        await queryRunner.query(`DROP TABLE "models"`);
        await queryRunner.query(`DROP TABLE "pre_app_survey"`);
        await queryRunner.query(`DROP TABLE "tokens"`);
        await queryRunner.query(`DROP TABLE "todos"`);
        await queryRunner.query(`DROP TABLE "vendors"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TABLE "invoice_items"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "scans"`);
        await queryRunner.query(`DROP TABLE "food_items"`);
        await queryRunner.query(`DROP TABLE "calories"`);
        await queryRunner.query(`DROP TABLE "big_five"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP TABLE "survey_scenarios"`);
        await queryRunner.query(`DROP TABLE "simulated_survey_scenarios"`);
        await queryRunner.query(`DROP TABLE "questions"`);
        await queryRunner.query(`DROP TABLE "question_options"`);
        await queryRunner.query(`DROP TABLE "user_answers"`);
        await queryRunner.query(`DROP TABLE "thread_halls"`);
        await queryRunner.query(`DROP TABLE "traits"`);
        await queryRunner.query(`DROP TABLE "behaviors"`);
        await queryRunner.query(`DROP TABLE "templates"`);
        await queryRunner.query(`DROP TABLE "template_answers"`);
        await queryRunner.query(`DROP TABLE "scenario_assignments"`);
    }

}
