name: production-deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start Tailscale and authenticate
        run: |
          sudo tailscaled &
          sleep 3
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}
          sleep 5

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      # Deploy Docker container
      - name: Deploy Docker container
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SSHPASS" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          
          set -e

          cd Greend_Mindmap_Backend

          echo "--- Pull latest image ---"
          docker pull iamqbao/green_mind_backend:latest

          echo "--- Remove old container ---"
          docker rm -f green-mind-backend || true

          echo "--- Run new container ---"
          docker run -d \
            --name green-mind-backend \
            --env-file /home/tnqbao/staging.env \
            -p 8080:8080 \
            iamqbao/green_mind_backend:latest

          echo "Deployment complete!"
          EOF
